apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-redis
  labels:
    service: vote-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      service: vote-redis
  template:
    metadata:
      labels:
        service: vote-redis
    spec:
      containers:
        - name: vote-redis
          image: redis:latest
          ports:
            - containerPort: 6379
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: vote-redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      protocol: TCP
  selector:
    service: vote-redis

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-db
  labels:
    service: result-db
spec:
  replicas: 1
  selector:
    matchLabels:
      service: result-db
  template:
    metadata:
      labels:
        service: result-db
    spec:
      containers:
        - name: result-db
          image: postgres:9.4
          ports:
            - containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"

---
apiVersion: v1
kind: Service
metadata:
  name: result-db
spec:
  type: ClusterIP
  ports:
    - port: 5432
      protocol: TCP
  selector:
    service: result-db

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app
  labels:
    service: worker-app
spec:
  replicas: 1
  selector:
    matchLabels:
      service: worker-app
  template:
    metadata:
      labels:
        service: worker-app
    spec:
      containers:
        - name: worker
          image: ghcr.io/subicura/voting/worker:latest
          env:
            - name: REDIS_HOST
              value: "vote-redis"
            - name: REDIS_PORT
              value: "6379"
            - name: POSTGRES_HOST
              value: "result-db"
            - name: POSTGRES_PORT
              value: "5432"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-app
  labels:
    service: vote-app
spec:
  replicas: 1
  selector:
    matchLabels:
      service: vote-app
  template:
    metadata:
      labels:
        service: vote-app
    spec:
      containers:
        - name: vote
          image: ghcr.io/subicura/voting/vote:latest
          env:
            - name: REDIS_HOST
              value: "vote-redis"
            - name: REDIS_PORT
              value: "6379"
          ports:
            - containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80

---
apiVersion: v1
kind: Service
metadata:
  name: vote-app
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      nodePort: 31000
  selector:
    service: vote-app

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app
  labels:
    service: result-app
spec:
  replicas: 1
  selector:
    matchLabels:
      service: result-app
  template:
    metadata:
      labels:
        service: result-app
    spec:
      containers:
        - name: result
          image: ghcr.io/subicura/voting/result:latest
          env:
            - name: POSTGRES_HOST
              value: "result-db"
            - name: POSTGRES_PORT
              value: "5432"
          ports:
            - containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80

---
apiVersion: v1
kind: Service
metadata:
  name: result-app
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      nodePort: 31001
  selector:
    service: result-app